# SPDX-License-Identifier: GPL-2.0-only

"""
nftables ruleset generator for the main `inet filter` table.

fwsec owns two tables:
  - `inet fwsec`   (managed by nft.py — allow/deny sets + hook chains)
  - `inet filter`  (managed here — SSH allow, crowdsec sets, default DROP)

`inet fwsec` chains run at priority -100 / -50, so they intercept traffic
before the `inet filter` chain (priority 0).
"""
from __future__ import annotations

from fwsec.config import FwsecConfig

FILTER_TABLE = "inet filter"


def generate_filter_table(cfg: FwsecConfig, ssh_port: int) -> str:
    """Generate the complete `inet filter` nftables config."""

    # Remove SSH port from tcp_in to avoid duplicate rule
    tcp_in_no_ssh = [p for p in cfg.tcp_in if p != str(ssh_port)]
    tcp_in_ports = _port_list(tcp_in_no_ssh)
    tcp_out_ports = _port_list(cfg.tcp_out)
    udp_in_ports = _port_list(cfg.udp_in)
    udp_out_ports = _port_list(cfg.udp_out)

    icmp_in = "ip protocol icmp accept" if cfg.icmp_in else ""
    icmp6_in = (
        'ip6 nexthdr icmpv6 icmpv6 type { echo-request, echo-reply, destination-unreachable, '
        'time-exceeded, nd-neighbor-solicit, nd-neighbor-advert } accept'
    ) if cfg.icmp_in and cfg.ipv6 else ""

    tcp_in_rule = f"tcp dport {{ {tcp_in_ports} }} ct state new accept" if tcp_in_ports else ""
    tcp_out_rule = f"tcp dport {{ {tcp_out_ports} }} ct state new accept" if tcp_out_ports else ""
    udp_in_rule = f"udp dport {{ {udp_in_ports} }} accept" if udp_in_ports else ""
    udp_out_rule = f"udp dport {{ {udp_out_ports} }} accept" if udp_out_ports else ""

    # Container/hypervisor mode: the forward chain must stay permissive so
    # container networking (Docker/Podman NAT) and VM networking (libvirt
    # NAT/routed, bridged with br_netfilter) keep working. CrowdSec bans still
    # apply to forwarded traffic; fwsec allow/deny forward chains live in
    # inet fwsec.
    if cfg.container_mode or cfg.hypervisor_mode:
        forward_chain = """\
    chain forward {
        type filter hook forward priority filter; policy accept;

        ct state established,related accept

        # CrowdSec bans also apply to forwarded (container) traffic
        ip  saddr @crowdsec-blacklists  drop
        ip6 saddr @crowdsec6-blacklists drop
    }"""
    else:
        forward_chain = """\
    chain forward {
        type filter hook forward priority filter; policy drop;
    }"""

    return f"""#!/usr/sbin/nft -f
# fwsec - inet filter table
# Generated by fwsec rules.py

# Create-if-missing so the flush never fails on a clean system
add table inet filter
flush table inet filter

table inet filter {{

    # CrowdSec bouncer sets (managed by crowdsec-firewall-bouncer)
    set crowdsec-blacklists {{
        type ipv4_addr
        flags timeout
    }}

    set crowdsec6-blacklists {{
        type ipv6_addr
        flags timeout
    }}

    chain input {{
        type filter hook input priority filter; policy drop;

        # Loopback
        iif "lo" accept

        # Established / related
        ct state established,related accept
        ct state invalid drop

        # ICMP
        {icmp_in}
        {icmp6_in}

        # CrowdSec bans (before port allows)
        ip  saddr @crowdsec-blacklists  drop
        ip6 saddr @crowdsec6-blacklists drop

        # SSH
        tcp dport {ssh_port} ct state new accept

        # Additional inbound TCP
        {tcp_in_rule}

        # Additional inbound UDP
        {udp_in_rule}
    }}

{forward_chain}

    chain output {{
        type filter hook output priority filter; policy accept;

        # Outbound TCP
        {tcp_out_rule}

        # Outbound UDP
        {udp_out_rule}
    }}
}}
"""


def generate_fwsec_table() -> str:
    """Generate the `inet fwsec` table (allow/deny sets + hook chains)."""
    return """#!/usr/sbin/nft -f
# fwsec - fwsec table (allow/deny lists)
# Generated by fwsec rules.py

table inet fwsec {

    set allow4 {
        type ipv4_addr
        flags interval
        auto-merge
    }

    set allow6 {
        type ipv6_addr
        flags interval
        auto-merge
    }

    set deny4 {
        type ipv4_addr
        flags interval, timeout
    }

    set deny6 {
        type ipv6_addr
        flags interval, timeout
    }

    # Whitelist: accept before main filter
    chain whitelist {
        type filter hook input priority -100; policy accept;
        ip  saddr @allow4 accept
        ip6 saddr @allow6 accept
    }

    # Blacklist: drop before main filter
    chain blacklist {
        type filter hook input priority -50; policy accept;
        ip  saddr @deny4 drop
        ip6 saddr @deny6 drop
    }

    # Same lists on the forward hook, so allow/deny also cover traffic
    # NATed to containers (published ports never traverse the input hook)
    chain whitelist_forward {
        type filter hook forward priority -100; policy accept;
        ip  saddr @allow4 accept
        ip6 saddr @allow6 accept
    }

    chain blacklist_forward {
        type filter hook forward priority -50; policy accept;
        ip  saddr @deny4 drop
        ip6 saddr @deny6 drop
    }
}
"""


def generate_container_filter(
    tcp_ports: list[int],
    udp_ports: list[int],
    subnets: list[str],
) -> str:
    """Generate the `containers` chain (CONTAINER_POLICY = filtered).

    Drops new connections to published container ports unless the source is
    in the allow list or in a container network. Published ports are DNATed
    before the forward hook, so matching uses the original (pre-NAT) port.
    """
    subnets4 = [s for s in subnets if ":" not in s]
    subnets6 = [s for s in subnets if ":" in s]

    lines = [
        "ip  saddr @allow4 accept",
        "ip6 saddr @allow6 accept",
        "ct state established,related accept",
    ]
    if subnets4:
        lines.append(f"ip saddr {{ {', '.join(sorted(subnets4))} }} accept")
    if subnets6:
        lines.append(f"ip6 saddr {{ {', '.join(sorted(subnets6))} }} accept")
    if tcp_ports:
        ports = ", ".join(str(p) for p in sorted(set(tcp_ports)))
        lines.append(f"meta l4proto tcp ct original proto-dst {{ {ports} }} ct state new drop")
    if udp_ports:
        ports = ", ".join(str(p) for p in sorted(set(udp_ports)))
        lines.append(f"meta l4proto udp ct original proto-dst {{ {ports} }} drop")

    body = "\n".join(f"        {line}" for line in lines)
    return f"""#!/usr/sbin/nft -f
# fwsec - published container port filter (CONTAINER_POLICY = filtered)
# Generated by fwsec rules.py

table inet fwsec {{
    chain containers {{
        type filter hook forward priority -60; policy accept;
{body}
    }}
}}
"""


def generate_vm_filter(subnets: list[str]) -> str:
    """Generate the `vms` chain (VM_POLICY = filtered).

    Drops new forwarded connections into libvirt NAT/routed VM subnets unless
    the source is in the allow list (or is another VM subnet, so VM outbound
    and inter-VM traffic keep working). Bridged VMs without br_netfilter are
    not subject to L3 hooks and cannot be covered here.
    """
    subnets4 = sorted(s for s in subnets if ":" not in s)
    subnets6 = sorted(s for s in subnets if ":" in s)

    lines = [
        "ip  saddr @allow4 accept",
        "ip6 saddr @allow6 accept",
        "ct state established,related accept",
    ]
    if subnets4:
        s4 = ", ".join(subnets4)
        lines.append(f"ip saddr {{ {s4} }} accept")
        lines.append(f"ip daddr {{ {s4} }} ct state new drop")
    if subnets6:
        s6 = ", ".join(subnets6)
        lines.append(f"ip6 saddr {{ {s6} }} accept")
        lines.append(f"ip6 daddr {{ {s6} }} ct state new drop")

    body = "\n".join(f"        {line}" for line in lines)
    return f"""#!/usr/sbin/nft -f
# fwsec - VM network filter (VM_POLICY = filtered)
# Generated by fwsec rules.py

table inet fwsec {{
    chain vms {{
        type filter hook forward priority -55; policy accept;
{body}
    }}
}}
"""


def _port_list(ports: list[str]) -> str:
    # Config files use 8000:8080 for ranges; nft expects 8000-8080
    return ", ".join(p.replace(":", "-") for p in ports)
