# SPDX-License-Identifier: GPL-2.0-only

"""
nftables ruleset generator for the main `inet filter` table.

fwsec owns two tables:
  - `inet fwsec`   (managed by nft.py — allow/deny sets + hook chains)
  - `inet filter`  (managed here — SSH allow, crowdsec sets, default DROP)

`inet fwsec` chains run at priority -100 / -50, so they intercept traffic
before the `inet filter` chain (priority 0).
"""
from __future__ import annotations

from fwsec.config import FwsecConfig

FILTER_TABLE = "inet filter"


def generate_filter_table(cfg: FwsecConfig, ssh_port: int) -> str:
    """Generate the complete `inet filter` nftables config."""

    # Remove SSH port from tcp_in to avoid duplicate rule
    tcp_in_no_ssh = [p for p in cfg.tcp_in if p != str(ssh_port)]
    tcp_in_ports = _port_list(tcp_in_no_ssh)
    tcp_out_ports = _port_list(cfg.tcp_out)
    udp_in_ports = _port_list(cfg.udp_in)
    udp_out_ports = _port_list(cfg.udp_out)

    icmp_in = "ip protocol icmp accept" if cfg.icmp_in else ""
    icmp6_in = (
        'ip6 nexthdr icmpv6 icmpv6 type { echo-request, echo-reply, destination-unreachable, '
        'time-exceeded, nd-neighbor-solicit, nd-neighbor-advert } accept'
    ) if cfg.icmp_in and cfg.ipv6 else ""

    tcp_in_rule = f"tcp dport {{ {tcp_in_ports} }} ct state new accept" if tcp_in_ports else ""
    tcp_out_rule = f"tcp dport {{ {tcp_out_ports} }} ct state new accept" if tcp_out_ports else ""
    udp_in_rule = f"udp dport {{ {udp_in_ports} }} accept" if udp_in_ports else ""
    udp_out_rule = f"udp dport {{ {udp_out_ports} }} accept" if udp_out_ports else ""

    return f"""#!/usr/sbin/nft -f
# fwsec - inet filter table
# Generated by fwsec rules.py

flush table inet filter

table inet filter {{

    # CrowdSec bouncer sets (managed by crowdsec-firewall-bouncer)
    set crowdsec-blacklists {{
        type ipv4_addr
        flags timeout
    }}

    set crowdsec6-blacklists {{
        type ipv6_addr
        flags timeout
    }}

    chain input {{
        type filter hook input priority filter; policy drop;

        # Loopback
        iif "lo" accept

        # Established / related
        ct state established,related accept
        ct state invalid drop

        # ICMP
        {icmp_in}
        {icmp6_in}

        # CrowdSec bans (before port allows)
        ip  saddr @crowdsec-blacklists  drop
        ip6 saddr @crowdsec6-blacklists drop

        # SSH
        tcp dport {ssh_port} ct state new accept

        # Additional inbound TCP
        {tcp_in_rule}

        # Additional inbound UDP
        {udp_in_rule}
    }}

    chain forward {{
        type filter hook forward priority filter; policy drop;
    }}

    chain output {{
        type filter hook output priority filter; policy accept;

        # Outbound TCP
        {tcp_out_rule}

        # Outbound UDP
        {udp_out_rule}
    }}
}}
"""


def generate_fwsec_table() -> str:
    """Generate the `inet fwsec` table (allow/deny sets + hook chains)."""
    return """#!/usr/sbin/nft -f
# fwsec - fwsec table (allow/deny lists)
# Generated by fwsec rules.py

table inet fwsec {

    set allow4 {
        type ipv4_addr
        flags interval
        auto-merge
    }

    set allow6 {
        type ipv6_addr
        flags interval
        auto-merge
    }

    set deny4 {
        type ipv4_addr
        flags timeout
    }

    set deny6 {
        type ipv6_addr
        flags timeout
    }

    # Whitelist: accept before main filter
    chain whitelist {
        type filter hook input priority -100; policy accept;
        ip  saddr @allow4 accept
        ip6 saddr @allow6 accept
    }

    # Blacklist: drop before main filter
    chain blacklist {
        type filter hook input priority -50; policy accept;
        ip  saddr @deny4 drop
        ip6 saddr @deny6 drop
    }
}
"""


def _port_list(ports: list[str]) -> str:
    return ", ".join(ports)
